name = "workout-energy-fitness"
compatibility_date = "2026-03-05"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "workout_energy_fitness_clean"
database_id = "fe30465f-1342-4145-9ad6-bfe90ce37358"
migrations_dir = "migrations"

[vars]
GOOGLE_CLIENT_ID = "545615642066-het2k28s5182f0hmvtqm1umvi945d8tf.apps.googleusercontent.com"
SESSION_COOKIE_NAME = "wef_session"
SESSION_TTL_HOURS = "720"
VITE_GOOGLE_CLIENT_ID = "545615642066-het2k28s5182f0hmvtqm1umvi945d8tf.apps.googleusercontent.com"
